config/routes.rb
Rails.application.routes.draw do

  ####  Welcome / hub

  root  'welcome#welcome'

  get   'consent' => 'welcome#consent'
  post  'consent' => 'welcome#consent'

  get   'hub' => 'welcome#hub'

  get   'print' => 'welcome#print'

  get   'follow-up' => 'welcome#follow_up'
  post  'follow-up' => 'welcome#follow_up'

  # Returning user

  get   'returning-user' => 'welcome#returning_user'
  post  'returning-user' => 'welcome#returning_user'

  get   'returning-user-q1' => 'welcome#returning_user_q1'
  post  'returning-user-q1' => 'welcome#returning_user_q1'

  get   'returning-user-q2' => 'welcome#returning_user_q2'
  post  'returning-user-q2' => 'welcome#returning_user_q2'

  get   'returning-user-q3' => 'welcome#returning_user_q3'
  post  'returning-user-q3' => 'welcome#returning_user_q3'

  get   'returning-user-q4' => 'welcome#returning_user_q4'
  post  'returning-user-q4' => 'welcome#returning_user_q4'

  get   'returning-user-q5' => 'welcome#returning_user_q5'
  post  'returning-user-q5' => 'welcome#returning_user_q5'

  ####  Basic health check

  get   'full-name' => 'basic#full_name'
  post  'full-name' => 'basic#full_name'

  get   'date-of-birth-and-gender' => 'basic#date_of_birth_and_gender'
  post  'date-of-birth-and-gender' => 'basic#date_of_birth_and_gender'

  get   'suburb' => 'basic#suburb'
  post  'suburb' => 'basic#suburb'

  get   'country-of-birth' => 'basic#country_of_birth'
  post  'country-of-birth' => 'basic#country_of_birth'

  get   'aboriginal' => 'basic#aboriginal'
  post  'aboriginal' => 'basic#aboriginal'

  get   'smoking' => 'basic#smoking'
  post  'smoking' => 'basic#smoking'

  get   'allergies' => 'basic#allergies'
  post  'allergies' => 'basic#allergies'

  get   'other-allergies' => 'basic#other_allergies'
  post  'other-allergies' => 'basic#other_allergies'

  get   'bmi' => 'basic#bmi'
  post  'bmi' => 'basic#bmi'
  get   'bmi-read' => 'basic#bmi_read'

  get   'has_diabetes' => 'basic#has_diabetes'
  post  'has_diabetes' => 'basic#has_diabetes'

  ####  Diabetes

  get   'diabetes-welcome' => 'diabetes#welcome'

  get   'diabetes-age-group' => 'diabetes#age_group'
  post  'diabetes-age-group' => 'diabetes#age_group'

  get   'diabetes-hereditary' => 'diabetes#hereditary'
  post  'diabetes-hereditary' => 'diabetes#hereditary'

  get   'diabetes-high-blood-glucose' => 'diabetes#high_blood_glucose'
  post  'diabetes-high-blood-glucose' => 'diabetes#high_blood_glucose'

  get   'diabetes-hbp-medication' => 'diabetes#hbp_medication'
  post  'diabetes-hbp-medication' => 'diabetes#hbp_medication'

  get   'diabetes-fruit-and-veg' => 'diabetes#fruit_and_veg'
  post  'diabetes-fruit-and-veg' => 'diabetes#fruit_and_veg'

  get   'diabetes-physical-activity' => 'diabetes#physical_activity'
  post  'diabetes-physical-activity' => 'diabetes#physical_activity'

  get   'diabetes-waist-measurement' => 'diabetes#waist_measurement'
  post  'diabetes-waist-measurement' => 'diabetes#waist_measurement'

  ####  Physical

  get   'physical-welcome' => 'physical#welcome'

  get   'physical-work-type' => 'physical#work_type'
  post  'physical-work-type' => 'physical#work_type'

  get   'physical-activity-exercise' => 'physical#activity_exercise'
  post  'physical-activity-exercise' => 'physical#activity_exercise'
  get   'physical-activity-cycling' => 'physical#activity_cycling'
  post  'physical-activity-cycling' => 'physical#activity_cycling'
  get   'physical-activity-walking' => 'physical#activity_walking'
  post  'physical-activity-walking' => 'physical#activity_walking'
  get   'physical-activity-housework' => 'physical#activity_housework'
  post  'physical-activity-housework' => 'physical#activity_housework'
  get   'physical-activity-gardening' => 'physical#activity_gardening'
  post  'physical-activity-gardening' => 'physical#activity_gardening'

  get   'physical-walking-pace' => 'physical#walking_pace'
  post  'physical-walking-pace' => 'physical#walking_pace'

  ####  Alcohol

  get   'alcohol-welcome' => 'alcohol#welcome'

  get   'alcohol-frequency' => 'alcohol#frequency'
  post  'alcohol-frequency' => 'alcohol#frequency'

  get   'alcohol-num-drinks' => 'alcohol#num_drinks'
  post  'alcohol-num-drinks' => 'alcohol#num_drinks'

  get   'alcohol-frequency-six-or-more' => 'alcohol#frequency_six_or_more'
  post  'alcohol-frequency-six-or-more' => 'alcohol#frequency_six_or_more'

  #### Data export

  get   'data' => 'data#index'
  post  'data-practice' => 'data#practice_export'
  post  'data-research' => 'data#research_export'

end

app/controllers/basic_controller.rb
class BasicController < ApplicationController

  def full_name
    session[:total_steps] = 9
    session[:current_step] = 1

    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to date_of_birth_and_gender_url
    end
  end

  def date_of_birth_and_gender
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to suburb_url
    end
  end

  def suburb
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to country_of_birth_url
    end
  end

  def country_of_birth
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to aboriginal_url
    end
  end

  def aboriginal
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to smoking_url
    end
  end

  def smoking
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to allergies_url
    end
  end

  def allergies
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1

      if @user_data.has_other_allergies?
        session[:total_steps] += 1
        redirect_to other_allergies_url
      else
        redirect_to bmi_url
      end
    end
  end

  def other_allergies
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to bmi_url
    end
  end

  def bmi
    if request.post?
      @user_data.update_bmi params[:user_data][:height], params[:user_data][:weight]
      redirect_to has_diabetes_url
    end
  end

  def bmi_read

    if Rails.configuration.x.enable_bmi_scales
      ReadBmiScalesJob.reset_scales
      ReadBmiScalesJob.perform_now @user_data
    else
      # Simulate pause while user uses scales...
      sleep 2

      # Set example data
      @user_data.weight = 75.6
      @user_data.height = 172
      @user_data.bmi = 24.5
      @user_data.bmi_recorded_at = Time.now
      @user_data.save
    end

    if @user_data.bmi.blank?
      render json: {}, status: 400
    elsif !@user_data.height.between?(100, 198) # cm
      # BMI scales sometimes return bad height reading of 198cm - also fail if less than 100cm
      render json: {}, status: 400
    else
      session[:current_step] += 1
      render json: {
        weight: @user_data.weight,
        height: @user_data.height,
        bmi: @user_data.bmi
      }
    end
  end

  def has_diabetes
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      @user_data.calc_basic_score
      redirect_to hub_url
    end
  end

end

app/views/basic/aboriginal.html.erb
<h1 class="center">Are you of Aboriginal, Torres Strait Islander,<br />Pacific Islander or Maori descent?</h1>

<table class="two-col"style="margin-top: 10rem;">
  <tr>
    <td style="text-align: right;">
      <div class="btn btn-secondary large" onclick="submit(1)">Yes</div>
    </td>
    <td>
      <div class="btn btn-secondary large"  onclick="submit(0)">No</div>
    </td>
  </tr>
</table>

<%= form_tag aboriginal_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[aboriginal]', '' %>
<% end %>

<script>
function submit(val) {
  $('#user_data_aboriginal').val(val);
  $('#form').submit();
}
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <span style="visibility: hidden;"><%= next_button "$('#form').submit();" %></span>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/basic/bmi.html.erb
<h1 class="center">Height and weight</h1>

<table id="instructions" class="two-col" style="width: 50%; margin: 6rem auto 0 auto;">
  <tr>
    <td style="text-align: center;vertical-align: middle;">
      <%= image_tag "stand_up_straight.svg", style: "height: 350px;" %>
    </td>
    <td style="vertical-align: middle;">
      <ol style="font-size: 2rem; line-height: 5rem;">
        <li>Stand on the scales</li>
        <li>Stand up straight</li>
        <li>Listen for a "beep"</li>
      </ol>
    </td>
  </tr>
</table>

<div id="results" style="display: none;">
  <% arrow_fill = "#bbb" %>
  <table class="datepicker">
    <tr>
      <td id="btn-height-add"><%= svg_use "#icon-arrow-up", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
      <td id="btn-weight-add"><%= svg_use "#icon-arrow-up", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
    </tr>
    <tr>
      <td>Your height<div id="height" style="margin-right: 1rem;"></div></td>
      <td>Your weight<div id="weight"></div></td>
    </tr>
    <tr>
      <td id="btn-height-minus"><%= svg_use "#icon-arrow-down", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
      <td id="btn-weight-minus"><%= svg_use "#icon-arrow-down", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
    </tr>
  </table>
</div>

<p style="text-align: center">Adjust your height and weight using the arrows if necessary</p>

<%= form_tag bmi_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[height]', '' %>
  <%= hidden_field_tag 'user_data[weight]', '' %>
<% end %>

<div id="retry-bmi-model-content" style="display: none;">
  <h1 class="center">Try measuring your<br/>height and weight again?</h1>
  <div style="text-align: center;margin: 3rem auto 4rem auto;">
    <p>There was a problem with measuring your height and weight.</p>
    <p>Would you like to try again?</p>
  </div>

  <table class="two-col" style="width: 30rem;">
    <tr>
      <td><button type="button" class="btn btn-primary" onclick="retryReadBmiData();return false;">Retry</button></td>
      <td style="text-align: right;"><button type="button" class="btn btn-secondary" onclick="gotoNext();return false;">Cancel</button></td>
    </tr>
  </table>
</div>
<%= render :partial => 'partials/modal' %>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "submit_values()" %>
<% end %>

<script>

var height, weight;
var retryDialogContent;
var retryCount = 0;
var MAX_BMI_READ_RETRIES = <%= Rails.configuration.x.max_bmi_scale_retries %>
var ajax_url = '<%= bmi_read_url %>';
var next_url = '<%= has_diabetes_url %>';

var REPEAT_SPEED = 333;
var repeatCallback= 0;

$(document).ready(function() {

  $('#btn-height-add').mousedown(function() { addHeight(); render(); repeatCallback = setInterval(function(){ addHeight(); render(); }, REPEAT_SPEED); return false; })
  $('#btn-height-minus').mousedown(function() {  minusHeight(); render(); repeatCallback = setInterval(function(){ minusHeight(); render(); }, REPEAT_SPEED); return false; })
  $('#btn-weight-add').mousedown(function() { addWeight(); render(); repeatCallback = setInterval(function(){ addWeight(); render(); }, REPEAT_SPEED); return false; })
  $('#btn-weight-minus').mousedown(function() {  minusWeight(); render(); repeatCallback = setInterval(function(){ minusWeight(); render(); }, REPEAT_SPEED); return false; })

  $(document).mouseup(function(){
    clearInterval(repeatCallback);
    return false;
  });

  retryDialogContent = $("#retry-bmi-model-content").detach();
  readBmiData();
});

function readBmiData() {
  $.ajax({
    url: ajax_url,
    success: function (data) {
        height = parseFloat(data.height);
        weight = parseFloat(data.weight);
        $('#instructions').hide();
        render();
        $('#results').show();
        $('#next').removeClass('disabled').attr('href', next_url);
    },
    error: function () {
      if (retryCount < MAX_BMI_READ_RETRIES) {
        showModal(retryDialogContent);
      } else {
        gotoNext();
      }
    }
  });
}

function retryReadBmiData() {
  retryCount++;
  resetSession();
  hideModal();
  readBmiData();
}

function gotoNext() {
  window.location = next_url;
}

function render() {
  $('#weight').text(weight + ' kg');
  $('#height').text(height + ' cm');
}

function addHeight() {
  height += 1;
  render();
}

function minusHeight() {
  height -= 1;
  render();
}

function addWeight() {
  weight += 0.5;
  render();
}

function minusWeight() {
  weight -= 0.5;
  render();
}

function submit_values() {
  $('#user_data_height').val(height);
  $('#user_data_weight').val(weight);
  $('#form').submit();
}

</script>

<%= render :partial => 'partials/timeout_modal' %>

app/views/basic/country_of_birth.html.erb
<h1 class="center">Country of birth</h1>

<div style="text-align: center; width: 45rem; margin: 3rem auto;">
  <ul class="options" data-option-group="user_data_country_of_birth" data-callback="validateForm" style="text-align: left;">
    <% UserData::REGIONS.each do |r| %>
    <li class="option" data-value="<%= r[:id] %>"><span></span><%= r[:name] %></li>
    <% end %>
  </ul>
</div>

<%= form_tag country_of_birth_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[country_of_birth]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/basic/date_of_birth_and_gender.html.erb
<script>

var MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
var START_YEAR = 1900;
var REPEAT_SPEED = 333;
var datePickerRepeat= 0;

var day = 1;
var month = 1;
var year = 1970;

function init() {

  $('.datepicker-btn-day-add').mousedown(function() { addDay(); render(); datePickerRepeat = setInterval(function(){ addDay(); render(); }, REPEAT_SPEED); return false; })
  $('.datepicker-btn-day-minus').mousedown(function() {  minusDay(); render(); datePickerRepeat = setInterval(function(){ minusDay(); render(); }, REPEAT_SPEED); return false; })

  $('.datepicker-btn-month-add').mousedown(function() { addMonth(); render(); datePickerRepeat = setInterval(function(){ addMonth(); render(); }, REPEAT_SPEED); return false; })
  $('.datepicker-btn-month-minus').mousedown(function() { minusMonth(); render(); datePickerRepeat = setInterval(function(){ minusMonth(); render(); }, REPEAT_SPEED); return false; })

  $('.datepicker-btn-year-add').mousedown(function() { addYear(); render(); datePickerRepeat = setInterval(function(){ addYear(); render(); }, REPEAT_SPEED); return false; })
  $('.datepicker-btn-year-minus').mousedown(function() { minusYear(); render(); datePickerRepeat = setInterval(function(){ minusYear(); render(); }, REPEAT_SPEED); return false; })

  $('.datepicker-value-day').click(function() { highlight('day') });
  $('.datepicker-value-month').click(function() { highlight('month') });
  $('.datepicker-value-year').click(function() { highlight('year') });

  $(document).mouseup(function(){
    clearInterval(datePickerRepeat);
    return false;
  });

  highlight('day');
  render();
}

function render() {
  $(".datepicker-value-day").text(day);
  $(".datepicker-value-month").text(MONTHS[month - 1]);
  $(".datepicker-value-year").text(year);
  $("#user_data_date_of_birth").val(year + '-' + month + '-' + day);
}

function highlight(field) {
  $(".datepicker-value").removeClass("selected");
  $(".datepicker-value-" + field).addClass("selected");
}

function addDay() {
  day++;
  if (day > 31) day = 1;
  highlight('day');
  render();
}

function minusDay() {
  day--;
  if (day < 1) day = 31;
  highlight('day');
  render();
}

function addMonth() {
  month++;
  if (month > 12) month = 1;
  highlight('month');
  render();
}

function minusMonth() {
  month--;
  if (month < 1) month = 12;
  highlight('month');
  render();
}

function addYear() {
  year++;
  if (year > (new Date().getFullYear())) year = 1;
  highlight('year');
  render();
}

function minusYear() {
  year--;
  if (year < START_YEAR) year = START_YEAR;
  highlight('year');
  render();
}

$(document).ready(function() { init(); });

</script>


<table class="two-col border">
  <tr>
    <td>
      <h1 class="center">Date of birth</h1>
      <% arrow_fill = "#bbb" %>
      <table class="datepicker">
        <tr>
          <td class="datepicker-btn-day-add"><%= svg_use "#icon-arrow-up", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
          <td class="datepicker-btn-month-add"><%= svg_use "#icon-arrow-up", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
          <td class="datepicker-btn-year-add"><%= svg_use "#icon-arrow-up", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
        </tr>
        <tr>
          <td><div class="datepicker-value datepicker-value-day">1</div></td>
          <td><div class="datepicker-value datepicker-value-month">Jan</div></td>
          <td><div class="datepicker-value datepicker-value-year">1970</div></td>
        </tr>
        <tr>
          <td class="datepicker-btn-day-minus"><%= svg_use "#icon-arrow-down", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
          <td class="datepicker-btn-month-minus"><%= svg_use "#icon-arrow-down", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
          <td class="datepicker-btn-year-minus"><%= svg_use "#icon-arrow-down", style: "fill: #{arrow_fill}; width: 5rem;" %></td>
        </tr>
      </table>
    </td>
    <td style="text-align: center;">
      <h1 class="center">Gender</h1>
      <div class="options" data-option-group="user_data_gender" data-callback="validateForm" style="margin: 6rem auto;text-align: center;">
        <div class="option" style="margin-right: 10rem; margin-bottom: 5rem;" data-value="<%= UserData::GENDERS[0][:id] %>">
          <%= svg_use "#icon-male", style: "fill: #111; width: 8rem; height: 16rem;" %>
        </div>
        <div class="option" style="margin-bottom: 5rem;" data-value="<%= UserData::GENDERS[1][:id] %>">
          <%= svg_use "#icon-female", style: "fill: #111; width: 9rem; height: 16rem;" %>
        </div>
        <div style="clear: both;"></div>
        <div class="option" style="display: inline-block;" data-value="<%= UserData::GENDERS[2][:id] %>"><%= UserData::GENDERS[2][:name] %></div>
      </div>
    </td>
  </tr>
</table>

<%= form_tag date_of_birth_and_gender_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[date_of_birth]', '' %>
  <%= hidden_field_tag 'user_data[gender]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/basic/full_name.html.erb
<h1 class="center">Your full name</h1>

<%= form_tag full_name_path, { :id => "form", :autocomplete => "off" } do |f| %>

  <div style="text-align: center; width: 75%; margin-left: auto; margin-right: auto;">
      <input type="text" id="full_name" name="user_data[full_name]" value=""
        placeholder="Full name, example: Jane Citizen" data-osk-options="disableReturn disableTab disableSymbols">
  </div>

<% end %>

<script>
$(document).ready(function() {
  full_name = $('#full_name');

  full_name.on('keyup', function() {
    var s = full_name.val().trim();
    if (s && (s.length > 6) && (s.indexOf(' ') >= 0)) {
      $('#next').removeClass('disabled');
    } else {
      $('#next').addClass('disabled');
    }
  });

  full_name.onScreenKeyboard({ topPosition: '28%', leftPosition: '19%'});
  full_name.click();
  full_name.focus();

});
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/basic/has_diabetes.html.erb
<h1 class="center">Have you ever been told by a doctor<br />or at a hospital you have diabetes?</h1>

<!-- Yes, No, (If Female additional option is Yes -only during pregnancy), Don’t know -->


<div style="text-align: center; width: 38rem; margin: 6rem auto;">
  <ul class="options" data-option-group="user_data_has_diabetes" data-callback="validateForm" style="text-align: left;">
    <% UserData::DIABETES.each do |d| %>
    <% if d[:female] && !@user_data.female? then %>
      <% next %>
    <% else %>
      <li class="option" data-value="<%= d[:id] %>"><span></span><%= d[:name] %></li>
    <% end %>
    <% end %>
  </ul>
</div>

<%= form_tag has_diabetes_url, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[has_diabetes]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();", "#", "Finish" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/basic/other_allergies.html.erb
<h1 class="center">Other allergies</h1>

<%= form_tag other_allergies_path, { :id => "form", :autocomplete => "off" } do |f| %>

  <div style="text-align: center; width: 75%; margin-left: auto; margin-right: auto;">
      <input type="text" id="other_allergies" name="user_data[other_allergies]" value=""
        placeholder="Example: Pollen" data-osk-options="disableReturn disableTab">
  </div>

<% end %>

<script>
$(document).ready(function() {
  field = $('#other_allergies');
  field.onScreenKeyboard({ topPosition: '28%', leftPosition: '19%'});
  field.click();
  field.focus();
  $("#next").removeClass("disabled");
});
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/basic/returning_user.html.erb
<h1 class="center">Have you used this Health Pod before?</h1>

<table class="two-col"style="margin-top: 10rem;">
  <tr>
    <td style="text-align: right;">
      <div class="btn btn-secondary large" onclick="submit(1)">Yes</div>
    </td>
    <td>
      <div class="btn btn-secondary large"  onclick="submit(0)">No</div>
    </td>
  </tr>
</table>

<%= form_tag returning_user_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[returning_user]', '' %>
<% end %>

<script>
function submit(val) {
  $('#user_data_returning_user').val(val);
  $('#form').submit();
}
</script>

<% content_for :footer_left do %>
  <label class="nav exit" for="exit-modal">Exit</label>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <span style="visibility: hidden;"><%= next_button "$('#form').submit();" %></span>
<% end %>

app/views/basic/smoking.html.erb
<h1 class="center">Do you currently smoke cigarettes or any<br />other tobacco products on a daily basis?</h1>

<div style="text-align: center; width: 38rem; margin: 6rem auto;">
  <ul class="options" data-option-group="user_data_smoking" data-callback="validateForm" style="text-align: left;">
    <% UserData::SMOKING.each do |s| %>
    <li class="option" data-value="<%= s[:id] %>"><span></span><%= s[:name] %></li>
    <% end %>
  </ul>
</div>

<%= form_tag smoking_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[smoking]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>