config/routes.rb
Rails.application.routes.draw do

  ####  Welcome / hub

  root  'welcome#welcome'

  get   'consent' => 'welcome#consent'
  post  'consent' => 'welcome#consent'

  get   'hub' => 'welcome#hub'

  get   'print' => 'welcome#print'

  get   'follow-up' => 'welcome#follow_up'
  post  'follow-up' => 'welcome#follow_up'

  # Returning user

  get   'returning-user' => 'welcome#returning_user'
  post  'returning-user' => 'welcome#returning_user'

  get   'returning-user-q1' => 'welcome#returning_user_q1'
  post  'returning-user-q1' => 'welcome#returning_user_q1'

  get   'returning-user-q2' => 'welcome#returning_user_q2'
  post  'returning-user-q2' => 'welcome#returning_user_q2'

  get   'returning-user-q3' => 'welcome#returning_user_q3'
  post  'returning-user-q3' => 'welcome#returning_user_q3'

  get   'returning-user-q4' => 'welcome#returning_user_q4'
  post  'returning-user-q4' => 'welcome#returning_user_q4'

  get   'returning-user-q5' => 'welcome#returning_user_q5'
  post  'returning-user-q5' => 'welcome#returning_user_q5'

  ####  Basic health check

  get   'full-name' => 'basic#full_name'
  post  'full-name' => 'basic#full_name'

  get   'date-of-birth-and-gender' => 'basic#date_of_birth_and_gender'
  post  'date-of-birth-and-gender' => 'basic#date_of_birth_and_gender'

  get   'suburb' => 'basic#suburb'
  post  'suburb' => 'basic#suburb'

  get   'country-of-birth' => 'basic#country_of_birth'
  post  'country-of-birth' => 'basic#country_of_birth'

  get   'aboriginal' => 'basic#aboriginal'
  post  'aboriginal' => 'basic#aboriginal'

  get   'smoking' => 'basic#smoking'
  post  'smoking' => 'basic#smoking'

  get   'allergies' => 'basic#allergies'
  post  'allergies' => 'basic#allergies'

  get   'other-allergies' => 'basic#other_allergies'
  post  'other-allergies' => 'basic#other_allergies'

  get   'bmi' => 'basic#bmi'
  post  'bmi' => 'basic#bmi'
  get   'bmi-read' => 'basic#bmi_read'

  get   'has_diabetes' => 'basic#has_diabetes'
  post  'has_diabetes' => 'basic#has_diabetes'

  ####  Diabetes

  get   'diabetes-welcome' => 'diabetes#welcome'

  get   'diabetes-age-group' => 'diabetes#age_group'
  post  'diabetes-age-group' => 'diabetes#age_group'

  get   'diabetes-hereditary' => 'diabetes#hereditary'
  post  'diabetes-hereditary' => 'diabetes#hereditary'

  get   'diabetes-high-blood-glucose' => 'diabetes#high_blood_glucose'
  post  'diabetes-high-blood-glucose' => 'diabetes#high_blood_glucose'

  get   'diabetes-hbp-medication' => 'diabetes#hbp_medication'
  post  'diabetes-hbp-medication' => 'diabetes#hbp_medication'

  get   'diabetes-fruit-and-veg' => 'diabetes#fruit_and_veg'
  post  'diabetes-fruit-and-veg' => 'diabetes#fruit_and_veg'

  get   'diabetes-physical-activity' => 'diabetes#physical_activity'
  post  'diabetes-physical-activity' => 'diabetes#physical_activity'

  get   'diabetes-waist-measurement' => 'diabetes#waist_measurement'
  post  'diabetes-waist-measurement' => 'diabetes#waist_measurement'

  ####  Physical

  get   'physical-welcome' => 'physical#welcome'

  get   'physical-work-type' => 'physical#work_type'
  post  'physical-work-type' => 'physical#work_type'

  get   'physical-activity-exercise' => 'physical#activity_exercise'
  post  'physical-activity-exercise' => 'physical#activity_exercise'
  get   'physical-activity-cycling' => 'physical#activity_cycling'
  post  'physical-activity-cycling' => 'physical#activity_cycling'
  get   'physical-activity-walking' => 'physical#activity_walking'
  post  'physical-activity-walking' => 'physical#activity_walking'
  get   'physical-activity-housework' => 'physical#activity_housework'
  post  'physical-activity-housework' => 'physical#activity_housework'
  get   'physical-activity-gardening' => 'physical#activity_gardening'
  post  'physical-activity-gardening' => 'physical#activity_gardening'

  get   'physical-walking-pace' => 'physical#walking_pace'
  post  'physical-walking-pace' => 'physical#walking_pace'

  ####  Alcohol

  get   'alcohol-welcome' => 'alcohol#welcome'

  get   'alcohol-frequency' => 'alcohol#frequency'
  post  'alcohol-frequency' => 'alcohol#frequency'

  get   'alcohol-num-drinks' => 'alcohol#num_drinks'
  post  'alcohol-num-drinks' => 'alcohol#num_drinks'

  get   'alcohol-frequency-six-or-more' => 'alcohol#frequency_six_or_more'
  post  'alcohol-frequency-six-or-more' => 'alcohol#frequency_six_or_more'

  #### Data export

  get   'data' => 'data#index'
  post  'data-practice' => 'data#practice_export'
  post  'data-research' => 'data#research_export'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def welcome
    reset_session
    @user_data = nil
  end

  def consent
    if request.post?
      consent = !params[:consent].blank?
      @user_data = UserData.new(consent: consent)
      @user_data.save

      if consent
        session[:user_data_id] = @user_data.id
        redirect_to returning_user_url
      else
        redirect_to root_url
      end
    end
  end

  def returning_user
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      if @user_data.returning_user
        redirect_to returning_user_q1_url
      else
        redirect_to hub_url
      end
    end
  end

  # Likert
  def returning_user_q1
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      redirect_to returning_user_q2_url
    end
  end

  # Did you discuss any health issues identified on your health report card with your GP, nurse, friends or family?
  def returning_user_q2
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      redirect_to returning_user_q3_url
    end
  end

  # Did you do any of the following after using the Health Pod?
  def returning_user_q3
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      if @user_data.returning_user_took_other_steps?
        redirect_to returning_user_q4_url
      else
        redirect_to returning_user_q5_url
      end
    end
  end

  # Other steps taken after using the Health Pod
  def returning_user_q4
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      redirect_to returning_user_q5_url
    end
  end

  # Did you visit the website shown on your health report card?
  def returning_user_q5
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      redirect_to hub_url
    end
  end

  def hub
  end

  def print
    report = ReportCard.new(@user_data)
    report.generate
    result = system("lp -d \"#{Rails.configuration.x.printer_name}\" -o media=A5 #{report.file_path}")
    unless result
      logger.error "Error printing health report card: #{result}"
    end
  end

  def follow_up
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      render "welcome/follow_up_done"
    end
  end

end

app/views/welcome/consent.html.erb
<h1>Confidentiality and consent</h1>
<table class="two-col border">
  <tr>
    <td>
      <h2 class="first">Confidentiality</h2>
      <p>Information collected will be kept strictly private and confidential. Your report card will be personalised but does not contain any details on it that will identify you. This study is being conducted by the Health Research Institute at the University of Canberra in collaboration with Ochre Health. If you have further questions about this research please contact the Chief Investigator: Dr Paresh Dawda, Ochre Health, Bruce.</p>
      <h2>Ethics</h2>
      <p>Ethics approval has been granted by University of Canberra Human Research Ethics Committee Project number 15-188.</p>
    </td>
    <td>
      <h2 class="first">Consent</h2>
      <div class="info">
        <ul>
          <li>I am aged over 18 years</li>
          <li>I am a patient at Ochre Health GP Clinic, Bruce</li>
          <li>I have read and understood the information on this page</li>
        </ul>
      </div>
    </td>
  </tr>
</table>

<%= form_tag consent_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'consent', '' %>
<% end %>

<% content_for :footer_left do %>
  <%= link_to "Disagree and exit", "#", class: "nav exit", onclick: "$('#form').submit();return false;" %>
<% end %>
<% content_for :footer_right do %>
  <%= link_to "Agree and proceed", "#", class: "nav next", onclick: "$('#consent').val('true');$('#form').submit();return false;" %>
<% end %>

app/views/welcome/follow_up.html.erb
<h1 class="center">Your contact details</h1>

<%= form_tag follow_up_path, { :id => "form", :autocomplete => "off" } do |f| %>

  <div style="text-align: center; width: 75%; margin-left: auto; margin-right: auto;">
      <input type="text" id="follow_up_contact_details" name="user_data[follow_up_contact_details]" value=""
        placeholder="Example: 0400 123 456 or jane@example.com" data-osk-options="disableReturn disableTab">
  </div>

<% end %>

<script>
$(document).ready(function() {
  full_name = $('#follow_up_contact_details');

  full_name.on('keyup', function() {
    if (full_name.val().trim().length > 2) {
      $('#next').removeClass('disabled');
    } else {
      $('#next').addClass('disabled');
    }
  });

  full_name.onScreenKeyboard({ topPosition: '28%', leftPosition: '19%'});
  full_name.click();
  full_name.focus();

});
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();", "#", "Finish" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/follow_up_done.html.erb
<h1 class="center">Thank you</h1>

<p style="text-align: center;">
  We'll be in touch soon
</p>

<script>
$(document).ready(function() {
  $("#next").removeClass("disabled");
});
</script>

<% content_for :footer_left do %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button nil, root_url, "Finish" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/hub.html.erb
<% available = @user_data.basic_complete? ? "available" : "" %>

<table class="hub">
  <tr>
    <td>
      <div class="report-card basic complete">
        <h1>Basic health check</h1>
        <% if @user_data.basic_complete? %>
          <div class="score">BMI <%= @user_data.bmi_score_name %></div>
          <div class="risk-scale">
            <span>Risk level</span><%= risk_image @user_data.bmi_risk_score %>
          </div>
        <% else %>
        <div style="margin: 4rem auto; text-align: center;">
          <%= link_to "Start", full_name_url, class: "btn next" %>
        </div>
        <% end %>
      </div>
    </td>
    <td>
      <% complete = @user_data.physical_complete? ? "complete" : "" %>
      <div class="report-card physical <%= available %> <%= complete %>">
        <h1>Physical activity</h1>
        <% if @user_data.basic_complete? && !@user_data.physical_complete? %>
          <div style="margin: 4rem auto; text-align: center;">
            <%= link_to "Start", physical_welcome_url, class: "btn btn-secondary" %>
            <p class="estimate">Takes about <%= UserData::PHYSICAL_SURVEY_ESTIMATE %></p>
          </div>
        <% elsif @user_data.physical_complete? %>
           <div class="score"><%= @user_data.physical_score_name %></div>
           <div class="risk-scale">
             <span>Risk level</span><%= risk_image @user_data.physical_risk_score %>
           </div>
        <% end %>
      </div>
    </td>
  </tr>
  <tr>
    <td>
      <%
        complete = @user_data.diabetes_complete? ? "complete" : ""
        diabetes_available = @user_data.basic_complete? && !@user_data.has_diabetes? ? "available" : ""
      %>
      <div class="report-card diabetes <%= diabetes_available %> <%= complete %>">
        <h1>Type 2 diabetes risk</h1>
        <% if @user_data.basic_complete? && !@user_data.diabetes_complete? && !@user_data.has_diabetes? %>
          <div style="margin: 4rem auto; text-align: center;">
            <%= link_to "Start", diabetes_welcome_url, class: "btn btn-secondary" %>
            <p class="estimate">Takes about <%= UserData::DIABETES_SURVEY_ESTIMATE %></p>
          </div>
        <% elsif @user_data.diabetes_complete? %>
           <div class="score"><%= @user_data.diabetes_score_name %></div>
           <div class="risk-scale">
             <span>Risk level</span><%= risk_image @user_data.diabetes_risk_score %>
           </div>
        <% end %>
      </div>
    </td>
    <td>
      <% complete = @user_data.alcohol_complete? ? "complete" : "" %>
      <div class="report-card alcohol <%= available %> <%= complete %>">
        <h1>Alcohol consumption</h1>
        <% if @user_data.basic_complete? && !@user_data.alcohol_complete? %>
          <div style="margin: 4rem auto; text-align: center;">
            <%= link_to "Start", alcohol_welcome_url, class: "btn btn-secondary" %>
            <p class="estimate">Takes about <%= UserData::ALCOHOL_SURVEY_ESTIMATE %></p>
          </div>
        <% elsif @user_data.alcohol_complete? %>
           <div class="score"><%= @user_data.alcohol_score_name %></div>
           <div class="risk-scale">
             <span>Risk level</span><%= risk_image @user_data.alcohol_risk_score %>
           </div>
        <% end %>
      </div>
    </td>
  </tr>
</table>

<script>
function disable(btn) {
  $(btn).text('Printing...').addClass('disabled');
}
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <% if @user_data.basic_complete? %>
    <!-- For more information and recommended next steps: &nbsp;&nbsp; -->
    <%= link_to "Print and Finish", print_url, class: "nav next", onclick: "disable(this); return true;" %>
  <% end %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/print.html.erb
<table class="two-col border">
  <tr>
    <td>
      <h1 class="center">Your report is printing</h1>
      <div style="text-align: center;">

        <p>Thank you for using the Health Pod.</p>
        <p>Please visit again to update your health report card.</p>
        <%= image_tag "logo.svg", style: "height: 200px; margin-top: 6.5rem;" %>
      </div>
    </td>
    <td>
      <h1 class="center">Can you help us?</h1>
      <div style="text-align: center;">
        <p>Your feedback is very important to us.</p>
        <p>Can we contact you to discuss your experience<br />with using the Health Pod?</p>
      </div>

      <table class="two-col" style="margin-top: 10rem;">
        <tr>
          <td style="text-align: right; border: none;">
            <%= link_to "Yes", follow_up_url, class: "btn btn-secondary large" %>
          </td>
          <td style="border: none;">
            <%= link_to "No", root_url, class: "btn btn-secondary large" %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

<% content_for :footer_left do %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/returning_user.html.erb
<h1 class="center">Have you used this Health Pod before?</h1>

<table class="two-col"style="margin-top: 10rem;">
  <tr>
    <td style="text-align: right;">
      <div class="btn btn-secondary large" onclick="submit(1)">Yes</div>
    </td>
    <td>
      <div class="btn btn-secondary large"  onclick="submit(0)">No</div>
    </td>
  </tr>
</table>

<%= form_tag returning_user_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[returning_user]', '' %>
<% end %>

<script>
function submit(val) {
  $('#user_data_returning_user').val(val);
  $('#form').submit();
}
</script>

<% content_for :footer_left do %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/returning_user_q1.html.erb
<h1 class="center">How do feel about the Health Pod?</h1>


<table class="likert">
  <tr class="scale">
    <td></td>
    <td>Disagree</td>
    <td></td>
    <td></td>
    <td></td>
    <td>Agree</td>
  </tr>
  <tr class="options" data-option-group="user_data_returning_user_q1a" data-callback="validateForm">
    <th>The Health Pod is easy to use</th>
    <% UserData::LIKERT.each do |i| %>
    <td><li class="option" data-value="<%= i[:id] %>"><span></span></li></td>
    <% end %>
  </tr>
  <tr class="options" data-option-group="user_data_returning_user_q1b" data-callback="validateForm">
    <th>I would like to use the Health Pod frequently</th>
    <% UserData::LIKERT.each do |i| %>
    <td><li class="option" data-value="<%= i[:id] %>"><span></span></li></td>
    <% end %>
  </tr>
  <tr class="options" data-option-group="user_data_returning_user_q1c" data-callback="validateForm">
    <th>I feel very confident using the Health Pod</th>
    <% UserData::LIKERT.each do |i| %>
    <td><li class="option" data-value="<%= i[:id] %>"><span></span></li></td>
    <% end %>
  </tr>
  <tr class="options" data-option-group="user_data_returning_user_q1d" data-callback="validateForm">
    <th>The Health Pod increases my awareness of my health</th>
    <% UserData::LIKERT.each do |i| %>
    <td><li class="option" data-value="<%= i[:id] %>"><span></span></li></td>
    <% end %>
  </tr>
  <tr class="options" data-option-group="user_data_returning_user_q1e" data-callback="validateForm">
    <th>The health report card provides useful information</th>
    <% UserData::LIKERT.each do |i| %>
    <td><li class="option" data-value="<%= i[:id] %>"><span></span></li></td>
    <% end %>
  </tr>
</table>

<%= form_tag returning_user_q1_url, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[returning_user_q1a]', '' %>
  <%= hidden_field_tag 'user_data[returning_user_q1b]', '' %>
  <%= hidden_field_tag 'user_data[returning_user_q1c]', '' %>
  <%= hidden_field_tag 'user_data[returning_user_q1d]', '' %>
  <%= hidden_field_tag 'user_data[returning_user_q1e]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/returning_user_q2.html.erb
<h1 class="center">Did you discuss any health issues identified on your<br/>health report card with any of the following people?</h1>

<ul class="checkbox-options" style="text-align: left;margin: 6rem auto;width: 25rem;" data-field="user_data_returning_user_q2">
  <li class="option" data-value="Doctor"><span></span>Doctor</li>
  <li class="option" data-value="Nurse"><span></span>Nurse</li>
  <li class="option" data-value="Friends"><span></span>Friends</li>
  <li class="option" data-value="Family"><span></span>Family</li>
  <li class="option" data-value="None of the above"><span></span>None of the above</li>
</ul>

<%= form_tag returning_user_q2_url, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[returning_user_q2]', '' %>
<% end %>

<script>
$(document).ready(function() {
  $('#next').removeClass('disabled');
});
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/returning_user_q3.html.erb
<h1 class="center">Did you do any of the following after using the Health Pod?</h1>

<ul class="checkbox-options" style="text-align: left;margin: 6rem auto;width: 44rem;" data-field="user_data_returning_user_q3">
  <li class="option" data-value="Engage in additional physical activity"><span></span>Engage in additional physical activity</li>
  <li class="option" data-value="Decrease alcohol consumption"><span></span>Decrease alcohol consumption</li>
  <li class="option" data-value="Reduce or attempt to quit smoking"><span></span>Reduce or attempt to quit smoking</li>
  <li class="option" data-value="Change diet"><span></span>Change diet</li>
  <li class="option" data-value="Other"><span></span>Other</li>
  <li class="option" data-value="None of the above"><span></span>None of the above</li>
</ul>

<%= form_tag returning_user_q3_url, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[returning_user_q3]', '' %>
<% end %>

<script>
$(document).ready(function() {
  $('#next').removeClass('disabled');
});
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/returning_user_q4.html.erb
<h1 class="center">What other steps did you take after using the health pod?</h1>

<%= form_tag returning_user_q4_url, { :id => "form", :autocomplete => "off" } do |f| %>

  <div style="text-align: center; width: 75%; margin-left: auto; margin-right: auto;">
      <input type="text" id="returning_user_q4" name="user_data[returning_user_q4]" value=""
        placeholder="" data-osk-options="disableReturn disableTab disableSymbols">
  </div>

<% end %>

<script>
$(document).ready(function() {
  $('#next').removeClass('disabled');
  field = $('#returning_user_q4');

  field.onScreenKeyboard({ topPosition: '28%', leftPosition: '19%'});
  field.click();
  field.focus();

});
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/returning_user_q5.html.erb
<h1 class="center">Did you visit the website shown on your health report card?</h1>

<table class="two-col"style="margin-top: 10rem;">
  <tr>
    <td style="text-align: right;">
      <div class="btn btn-secondary large" onclick="submit(1)">Yes</div>
    </td>
    <td>
      <div class="btn btn-secondary large"  onclick="submit(0)">No</div>
    </td>
  </tr>
</table>

<%= form_tag returning_user_q5_url, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[returning_user_q5]', '' %>
<% end %>

<script>
function submit(val) {
  $('#user_data_returning_user_q5').val(val);
  $('#form').submit();
}
</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: root_url } %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <span style="visibility: hidden;"><%= next_button "$('#form').submit();" %></span>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/welcome/welcome.html.erb
<table class="two-col" style="width: 100%; margin-top: 4rem;">
  <tr>
    <td class="right" style="width: 40%; vertical-align: top;">
      <%= image_tag "logo.svg", style: "height: 250px;" %>
    </td>
    <td style="width: 60%; padding-top: 2rem; padding-right: 14rem">
      <div class="title">Welcome</div>
      <p>This Health Pod gives you an easy way to keep track of your personal health by collecting some basic health information.</p>
      <p>After answering a few questions and measuring your height and weight, you will receive a personalised health report card
        that you can take home or discuss with your health professional at your next appointment.</p>
      <p>You are welcome to return to the Pod at any time to add additional information and update your report card.</p>
      <p>Press start to begin.</p>
    </td>
  </tr>
</table>

<% content_for :footer_right do %>
  <%= link_to "Start", consent_path, class: "nav next" %>
<% end %>