config/routes.rb
Rails.application.routes.draw do

  ####  Welcome / hub

  root  'welcome#welcome'

  get   'consent' => 'welcome#consent'
  post  'consent' => 'welcome#consent'

  get   'hub' => 'welcome#hub'

  get   'print' => 'welcome#print'

  get   'follow-up' => 'welcome#follow_up'
  post  'follow-up' => 'welcome#follow_up'

  # Returning user

  get   'returning-user' => 'welcome#returning_user'
  post  'returning-user' => 'welcome#returning_user'

  get   'returning-user-q1' => 'welcome#returning_user_q1'
  post  'returning-user-q1' => 'welcome#returning_user_q1'

  get   'returning-user-q2' => 'welcome#returning_user_q2'
  post  'returning-user-q2' => 'welcome#returning_user_q2'

  get   'returning-user-q3' => 'welcome#returning_user_q3'
  post  'returning-user-q3' => 'welcome#returning_user_q3'

  get   'returning-user-q4' => 'welcome#returning_user_q4'
  post  'returning-user-q4' => 'welcome#returning_user_q4'

  get   'returning-user-q5' => 'welcome#returning_user_q5'
  post  'returning-user-q5' => 'welcome#returning_user_q5'

  ####  Basic health check

  get   'full-name' => 'basic#full_name'
  post  'full-name' => 'basic#full_name'

  get   'date-of-birth-and-gender' => 'basic#date_of_birth_and_gender'
  post  'date-of-birth-and-gender' => 'basic#date_of_birth_and_gender'

  get   'suburb' => 'basic#suburb'
  post  'suburb' => 'basic#suburb'

  get   'country-of-birth' => 'basic#country_of_birth'
  post  'country-of-birth' => 'basic#country_of_birth'

  get   'aboriginal' => 'basic#aboriginal'
  post  'aboriginal' => 'basic#aboriginal'

  get   'smoking' => 'basic#smoking'
  post  'smoking' => 'basic#smoking'

  get   'allergies' => 'basic#allergies'
  post  'allergies' => 'basic#allergies'

  get   'other-allergies' => 'basic#other_allergies'
  post  'other-allergies' => 'basic#other_allergies'

  get   'bmi' => 'basic#bmi'
  post  'bmi' => 'basic#bmi'
  get   'bmi-read' => 'basic#bmi_read'

  get   'has_diabetes' => 'basic#has_diabetes'
  post  'has_diabetes' => 'basic#has_diabetes'

  ####  Diabetes

  get   'diabetes-welcome' => 'diabetes#welcome'

  get   'diabetes-age-group' => 'diabetes#age_group'
  post  'diabetes-age-group' => 'diabetes#age_group'

  get   'diabetes-hereditary' => 'diabetes#hereditary'
  post  'diabetes-hereditary' => 'diabetes#hereditary'

  get   'diabetes-high-blood-glucose' => 'diabetes#high_blood_glucose'
  post  'diabetes-high-blood-glucose' => 'diabetes#high_blood_glucose'

  get   'diabetes-hbp-medication' => 'diabetes#hbp_medication'
  post  'diabetes-hbp-medication' => 'diabetes#hbp_medication'

  get   'diabetes-fruit-and-veg' => 'diabetes#fruit_and_veg'
  post  'diabetes-fruit-and-veg' => 'diabetes#fruit_and_veg'

  get   'diabetes-physical-activity' => 'diabetes#physical_activity'
  post  'diabetes-physical-activity' => 'diabetes#physical_activity'

  get   'diabetes-waist-measurement' => 'diabetes#waist_measurement'
  post  'diabetes-waist-measurement' => 'diabetes#waist_measurement'

  ####  Physical

  get   'physical-welcome' => 'physical#welcome'

  get   'physical-work-type' => 'physical#work_type'
  post  'physical-work-type' => 'physical#work_type'

  get   'physical-activity-exercise' => 'physical#activity_exercise'
  post  'physical-activity-exercise' => 'physical#activity_exercise'
  get   'physical-activity-cycling' => 'physical#activity_cycling'
  post  'physical-activity-cycling' => 'physical#activity_cycling'
  get   'physical-activity-walking' => 'physical#activity_walking'
  post  'physical-activity-walking' => 'physical#activity_walking'
  get   'physical-activity-housework' => 'physical#activity_housework'
  post  'physical-activity-housework' => 'physical#activity_housework'
  get   'physical-activity-gardening' => 'physical#activity_gardening'
  post  'physical-activity-gardening' => 'physical#activity_gardening'

  get   'physical-walking-pace' => 'physical#walking_pace'
  post  'physical-walking-pace' => 'physical#walking_pace'

  ####  Alcohol

  get   'alcohol-welcome' => 'alcohol#welcome'

  get   'alcohol-frequency' => 'alcohol#frequency'
  post  'alcohol-frequency' => 'alcohol#frequency'

  get   'alcohol-num-drinks' => 'alcohol#num_drinks'
  post  'alcohol-num-drinks' => 'alcohol#num_drinks'

  get   'alcohol-frequency-six-or-more' => 'alcohol#frequency_six_or_more'
  post  'alcohol-frequency-six-or-more' => 'alcohol#frequency_six_or_more'

  #### Data export

  get   'data' => 'data#index'
  post  'data-practice' => 'data#practice_export'
  post  'data-research' => 'data#research_export'

end

app/controllers/alcohol_controller.rb
class AlcoholController < ApplicationController

  def welcome
    session[:total_steps] = 3
    session[:current_step] = 1
  end

  def frequency
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?

      if @user_data.non_drinker?
        @user_data.calc_alcohol_score
        redirect_to hub_url
      else
        session[:current_step] += 1
        redirect_to alcohol_num_drinks_url
      end
    end
  end

  def num_drinks
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      session[:current_step] += 1
      redirect_to alcohol_frequency_six_or_more_url
    end
  end

  def frequency_six_or_more
    if request.post?
      @user_data.update_attributes(user_data_params) unless params[:user_data].blank?
      @user_data.calc_alcohol_score
      redirect_to hub_url
    end
  end

end

app/views/alcohol/frequency.html.erb
<h1 class="center">How often do you have a drink containing alcohol?</h1>

<div style="text-align: center; width: 30rem; margin: 6rem auto;">
  <ul class="options" data-option-group="user_data_alcohol_frequency" data-callback="validateForm" style="text-align: left;">
    <% UserData::ALCOHOL_FREQUENCY.each do |r| %>
    <li class="option" data-value="<%= r[:id] %>"><span></span><%= r[:name] %></li>
    <% end %>
  </ul>
</div>

<%= form_tag alcohol_frequency_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[alcohol_frequency]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: hub_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/alcohol/frequency_six_or_more.html.erb
<h1 class="center">How often do you have six or more drinks on one occasion?</h1>

<div style="text-align: center; width: 36rem; margin: 6rem auto;">
  <ul class="options" data-option-group="user_data_alcohol_frequency_six_or_more" data-callback="validateForm" style="text-align: left;">
    <% UserData::ALCOHOL_FREQUENCY_SIX_OR_MORE.each do |r| %>
    <li class="option" data-value="<%= r[:id] %>"><span></span><%= r[:name] %></li>
    <% end %>
  </ul>
</div>

<%= form_tag alcohol_frequency_six_or_more_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[alcohol_frequency_six_or_more]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: hub_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();", "#", "Finish" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/alcohol/num_drinks.html.erb
<h1 class="center">How many drinks do you have on a typical day?</h1>

<table class="" style="margin: 6rem auto;">
  <tr>
    <td style="vertical-align: middle; text-align: right;padding-right: 6rem;">
      <%= image_tag "drink_sizes.svg", style: "width: 42rem;" %>
    </td>
    <td>
      <ul class="options" data-option-group="user_data_alcohol_num_drinks" data-callback="validateForm" style="text-align: left;">
        <% UserData::ALCOHOL_NUM_DRINKS.each do |r| %>
        <li class="option" data-value="<%= r[:id] %>"><span></span><%= r[:name] %></li>
        <% end %>
      </ul>
    </td>
  </tr>
</table>

<%= form_tag alcohol_num_drinks_path, { :id => "form", :autocomplete => "off" } do |f| %>
  <%= hidden_field_tag 'user_data[alcohol_num_drinks]', '' %>
<% end %>

<script>

function validateForm(val) {
  $('#next').removeClass('disabled');
}

</script>

<% content_for :footer_left do %>
  <%= render :partial => 'partials/exit_modal', locals: { exit_url: hub_url } %>
<% end %>
<% content_for :footer_center do %>
  <%= progress_bar %>
<% end %>
<% content_for :footer_right do %>
  <%= next_button "$('#form').submit();" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>

app/views/alcohol/welcome.html.erb
<h1 class="center">
  <%= image_tag "alcohol.svg", style: "height: 100px;" %>
  Check your alcohol consumption
</h1>

<p style="text-align: center;margin: 5rem auto;">
  This survey will take about <%= UserData::ALCOHOL_SURVEY_ESTIMATE %> to complete
</p>

<% content_for :footer_left do %>
  <%= link_to hub_url, class: "nav exit" do %>
    <%= image_tag 'chevron-thin-left.svg' %>
    Back to health report
  <% end %>
<% end %>
<% content_for :footer_center do %>
<% end %>
<% content_for :footer_right do %>
  <%= link_to "Next", alcohol_frequency_path, class: "nav next" %>
<% end %>

<%= render :partial => 'partials/timeout_modal' %>